baseURL = "//www.marcuskirsch.de/"
languageCode = "en-us"
title = "Marcus Kirsch"
theme="hugo-split-theme"

disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]

# Copyright
copyright = "&copy;2019 Marcus Kirsch"

[params]

  # Metadata for search engines and social sharing
  author = "Marcus Kirsch"
  description = "Marcus Kirsch's Website"
  shareImage = "images/social.jpg"

  # Favicon
  favicon = "favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/marcus-kirsch-background.jpg"
      position = "center center"
  [[params.links]]

  [params.links.list1]
    heading = "Connect"

    [[params.links.list1.link]]
      text = "Email"
      url = "mailto:briefkasten@marcuskirsch.de"

    [[params.links.list1.link]]
      text = "Github"
      url = "https://github.com/marcuskirsch/"
